### ISSUE TITLE
Inject AuthorizationChecker into controller

### ISSUE THREAD

**Issue by izziaraffaele** [barryvdh/laravel-security#3]
I'm trying to check if a user has granted some role into my controller without using the helper or the facade but just injecting the AuthorizationChecker into my controller method. 

Injecting  `Symfony\Component\Security\Core\Authorization\AuthorizationChecker` I get :

```
BindingResolutionException in Container.php line 744:
Target [Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface] is not instantiable.
```

Is there a way to inject the AuthorizationChecker as dependency of my controller's methods?

**Comment by barryvdh** [comment]
Did https://github.com/barryvdh/laravel-security/commit/50cecd0728cc495f6055a09ed44d8501588ad9d6 fix it?

**Comment by izziaraffaele** [comment]
Yes, thanks a lot for the quick fix ;)
