### ISSUE TITLE
Update composer.json for illuminate/support 5.2 or 5.3

### ISSUE THREAD

**Issue by jszobody** [barryvdh/laravel-security#6]
Right now composer.json requires illuminate/support 5.0 or 5.1, can this support 5.2 and 5.3 as well?

Maybe even `^5.0`?

**Comment by barryvdh** [comment]
See https://github.com/barryvdh/laravel-security/commit/205a4cb95cd428d6faefcc57c95e756f2dad6713
You can try by requiring `0.2.x@dev`. If all good, I'll tag a new release.

**Comment by jszobody** [comment]
Yep, that did it. Thank you.
